### ISSUE TITLE
Didn't find class com.google.android.gms.common.internal.zzbo

### ISSUE THREAD

**Issue by kerberosargos** [hansemannn/titanium-firebase-core#37]
Hello my ti.playservices version was 11.0.40 I upgraded it to 16.1.2. After that I am getting error as below I have tried 16.1.0 too result is same. My jira ticket is [https://jira.appcelerator.org/browse/AC-6141](https://jira.appcelerator.org/browse/AC-6141)

```
02-27 13:00:30.485 12645 12645 E AndroidRuntime: FATAL EXCEPTION: main
02-27 13:00:30.485 12645 12645 E AndroidRuntime: Process: com.sizebiz.just.live.basketball, PID: 12645
02-27 13:00:30.485 12645 12645 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbo;
02-27 13:00:30.485 12645 12645 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2)
02-27 13:00:30.485 12645 12645 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6414)
02-27 13:00:30.485 12645 12645 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5961)
02-27 13:00:30.485 12645 12645 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5867)
02-27 13:00:30.485 12645 12645 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
02-27 13:00:30.485 12645 12645 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
02-27 13:00:30.485 12645 12645 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-27 13:00:30.485 12645 12645 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
02-27 13:00:30.485 12645 12645 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6692)
02-27 13:00:30.485 12645 12645 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-27 13:00:30.485 12645 12645 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-27 13:00:30.485 12645 12645 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-27 13:00:30.485 12645 12645 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbo" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.sizebiz.just.live.basketball-Rn8Kb-p0JpC_xcova1olLg==/base.apk"],nativeLibraryDirectories=[/data/app/com.sizebiz.just.live.basketball-Rn8Kb-p0JpC_xcova1olLg==/lib/arm64, /data/app/com.sizebiz.just.live.basketball-Rn8Kb-p0JpC_xcova1olLg==/base.apk!/lib/arm64-v8a, /system/lib64]]
02-27 13:00:30.485 12645 12645 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
02-27 13:00:30.485 12645 12645 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-27 13:00:30.485 12645 12645 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-27 13:00:30.485 12645 12645 E AndroidRuntime: 	... 12 more
02-27 13:00:30.487  2047  9545 W ActivityManager:   Force finishing activity com.sizebiz.just.live.basketball/.JustLiveBasketballActivity
```

My project's all module list as below

```
<modules>
<module platform="android">ti.playservices</module>
<module platform="iphone" version="1.0">ti.module.share</module>
<module platform="android" version="1.0.0">bencoding.android.tools</module>
<module platform="iphone" version="2.4.0">ti.admob</module>
<module platform="iphone" version="1.5.0">av.imageview</module>
<module platform="android" version="3.3.0">av.imageview</module>
<module platform="iphone" version="2.0.1">firebase.cloudmessaging</module>
<module platform="android" version="1.3.2">firebase.cloudmessaging</module>
<module platform="iphone" version="2.1.0">firebase.core</module>
<module platform="android" version="3.0.0">firebase.core</module>
<module platform="android" version="4.2.0">ti.android.admob</module>
<module platform="android" version="4.0.1">ti.ga</module>
<module platform="iphone" version="3.0.2">ti.ga</module>
</modules>

```

**Comment by hansemannn** [comment]
As noted in the other repo, there is an open PR to support PlayServices 16.x. You can follow the pull for details.
