### ISSUE TITLE
Android: Failed resolution of: Lcom/google/android/gms/common/internal/zzby

### ISSUE THREAD

**Issue by m1ga** [hansemannn/titanium-firebase-core#4]
```javascript
// Require the Firebase Core module
var FirebaseCore = require('firebase.core');

// Configure your Firebase API's (only required once for all)
FirebaseCore.configure();
$.index.open();
```
with only the firebase.core module produces this error when the app starts:

```
[INFO]  art: Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.zza>
[INFO]  art: Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.zza>
[WARN]  W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzby;
[WARN]  W/System.err: 	at com.google.firebase.FirebaseOptions.fromResource(Unknown Source)
[WARN]  W/System.err: 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
[WARN]  W/System.err: 	at firebase.core.TitaniumFirebaseCoreModule.configure(TitaniumFirebaseCoreModule.java:43)
[WARN]  W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native Method)
[WARN]  W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:196)
[WARN]  W/System.err: 	at org.appcelerator.kroll.KrollRuntime.runModule(KrollRuntime.java:243)
[WARN]  W/System.err: 	at org.appcelerator.titanium.TiLaunchActivity.loadActivityScript(TiLaunchActivity.java:128)
[WARN]  W/System.err: 	at org.appcelerator.titanium.TiLaunchActivity.windowCreated(TiLaunchActivity.java:183)
[WARN]  W/System.err: 	at org.appcelerator.titanium.TiRootActivity.windowCreated(TiRootActivity.java:172)
[WARN]  W/System.err: 	at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:684)
[WARN]  W/System.err: 	at org.appcelerator.titanium.TiLaunchActivity.onCreate(TiLaunchActivity.java:169)
[WARN]  W/System.err: 	at org.appcelerator.titanium.TiRootActivity.onCreate(TiRootActivity.java:161)
[WARN]  W/System.err: 	at android.app.Activity.performCreate(Activity.java:5990)
[WARN]  W/System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
[WARN]  W/System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
[WARN]  W/System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
[WARN]  W/System.err: 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
[WARN]  W/System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
[WARN]  W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[WARN]  W/System.err: 	at android.os.Looper.loop(Looper.java:135)
[WARN]  W/System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5254)
[WARN]  W/System.err: 	at java.lang.reflect.Method.invoke(Native Method)
[WARN]  W/System.err: 	at java.lang.reflect.Method.invoke(Method.java:372)
[WARN]  W/System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
[WARN]  W/System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
[WARN]  W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzby" on path: DexPathList[[zip file "/data/app/de.oevermann.analytics-1/base.apk"],nativeLibraryDirectories=[/data/app/de.oevermann.analytics-1/lib/arm, /vendor/lib, /system/lib]]
[WARN]  W/System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
[WARN]  W/System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
[WARN]  W/System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
[WARN]  W/System.err: 	... 25 more
[WARN]  W/System.err: 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.common.internal.zzby
[WARN]  W/System.err: 		at java.lang.Class.classForName(Native Method)
[WARN]  W/System.err: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
[WARN]  W/System.err: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
[WARN]  W/System.err: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
[WARN]  W/System.err: 		... 26 more
[WARN]  W/System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
[ERROR] TiExceptionHandler: (main) [312,312] ----- Titanium Javascript Runtime Error -----
[ERROR] TiExceptionHandler: (main) [0,312] - In /alloy/controllers/index.js:37,15
[ERROR] TiExceptionHandler: (main) [0,312] - Message: Uncaught Failed resolution of: Lcom/google/android/gms/common/internal/zzby;
[ERROR] TiExceptionHandler: (main) [0,312] - Source: 	FirebaseCore.configure();
[ERROR] V8Exception: Exception occurred at /alloy/controllers/index.js:37: Uncaught Failed resolution of: Lcom/google/android/gms/common/internal/zzby;
[ERROR] V8Exception: Failed resolution of: Lcom/google/android/gms/common/internal/zzby;
```

**Comment by m1ga** [comment]
fixed it by recompiling the https://github.com/appcelerator-modules/ti.playservices for 6.0.0 (just a manifest change) and including it into the project. I'll make a PR for the README!

**Comment by stefanovic72** [comment]
Hi, 

I get exactly the same error when I use the firebase.core module for android:
Failed resolution of: Lcom/google/android/gms/common/internal/zzby;

Do I need the ti.playservices module?
Strange thing, the ti.playservices has as requirement:
Titanium Mobile SDK 6.3.1.GA or later

But the latest Titanium SDK at the moment is 6.3.0 as far as I know.

Do you know how to get rid of the error message that i get when using the Firebase.core module?

**Comment by m1ga** [comment]
@stefanovic72 see my comment about. You have to recompile ti.playservices (it will be available for SDK 7 https://github.com/appcelerator-modules/ti.playservices/blob/master/android/manifest#L17) to use it with 6.3.0. To do that you need to change the minsdk version and recompile it. 
I've only tried the Analytics module but wasn't able to use it even the modules compiled fine. So depending on your use-case you'll still have to use a different module
